// <auto-generated />
using System;
using ASM_NET104_WedQuanAn.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASM_NET104_WedQuanAn.Migrations
{
    [DbContext(typeof(ASMFINALContext))]
    [Migration("20210302114022_ASMFINAL")]
    partial class ASMFINAL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASM_NET104_WedQuanAn.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("DiaChiKh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DiaChiKH");

                    b.Property<string>("EmailKh")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EmailKH");

                    b.Property<DateTime>("NgayHD")
                        .HasColumnType("Date")
                        .HasColumnName("NgayHD");

                    b.Property<string>("Sdtkh")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDTKH");

                    b.Property<string>("Tenkh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENKH");

                    b.HasKey("Id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("ASM_NET104_WedQuanAn.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("MaTd")
                        .HasColumnType("int")
                        .HasColumnName("MaTD");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id", "MaTd");

                    b.HasIndex("MaTd");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("ASM_NET104_WedQuanAn.Models.Nhom", b =>
                {
                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhom");

                    b.ToTable("Nhom");
                });

            modelBuilder.Entity("ASM_NET104_WedQuanAn.Models.ThucDon", b =>
                {
                    b.Property<int>("MaTd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTD")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Hinh")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nhom")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenTd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenTD");

                    b.HasKey("MaTd");

                    b.HasIndex("Nhom");

                    b.ToTable("ThucDon");
                });

            modelBuilder.Entity("ASM_NET104_WedQuanAn.Models.User", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserEmail");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ASM_NET104_WedQuanAn.Models.CartItem", b =>
                {
                    b.HasOne("ASM_NET104_WedQuanAn.Models.Cart", "IdNavigation")
                        .WithMany("CartItems")
                        .HasForeignKey("Id")
                        .HasConstraintName("fk_ct_hang")
                        .IsRequired();

                    b.HasOne("ASM_NET104_WedQuanAn.Models.ThucDon", "MaTdNavigation")
                        .WithMany("CartItems")
                        .HasForeignKey("MaTd")
                        .HasConstraintName("fk_ct_td")
                        .IsRequired();

                    b.Navigation("IdNavigation");

                    b.Navigation("MaTdNavigation");
                });

            modelBuilder.Entity("ASM_NET104_WedQuanAn.Models.ThucDon", b =>
                {
                    b.HasOne("ASM_NET104_WedQuanAn.Models.Nhom", "NhomNavigation")
                        .WithMany("ThucDons")
                        .HasForeignKey("Nhom")
                        .HasConstraintName("FK_ThucDon_nhom")
                        .IsRequired();

                    b.Navigation("NhomNavigation");
                });

            modelBuilder.Entity("ASM_NET104_WedQuanAn.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ASM_NET104_WedQuanAn.Models.Nhom", b =>
                {
                    b.Navigation("ThucDons");
                });

            modelBuilder.Entity("ASM_NET104_WedQuanAn.Models.ThucDon", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
